Adst 484
Alfresco/alfresco-ios-swift-api pull request #169
Opened 2024-07-05 14:01 UTC by PiplaniVinay

2024-07-05 17:37 UTC, aman-alfresco requested changes

2024-07-05 17:37 UTC, aman-alfresco commented on AlfrescoAuth/Sources/PKCE Authentication/AuthPkcePresenter.swift
> +            guard let data = data else {
Please correct the naming convention for **guard let data**

2024-07-06 13:27 UTC, gl-lovekesh requested changes
please check the suggestions

2024-07-06 13:27 UTC, gl-lovekesh commented on AlfrescoAuth/Sources/PKCE Authentication/AuthPkcePresenter.swift
> +            if let error = error {
```suggestion
            if let err = error {
```

2024-07-06 13:27 UTC, gl-lovekesh commented on AlfrescoAuth/Sources/PKCE Authentication/AuthPkcePresenter.swift
> +            guard let data = data else {
```suggestion
            guard let resData = data else {
```

2024-07-08 09:14 UTC, gl-lovekesh approved these changes
LGTM

2024-07-08 10:35 UTC, merged